# -*- coding: utf-8 -*-
"""cos_similarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YgmTexi4yI6JI3ayxejgEm4J-7j9Jl3e
"""

# 必要なライブラリのインポート
from scipy.spatial.distance import cosine 
import pandas as pd

# 質問を回答したcsvファイルの読み込み
df = pd.read_csv('./cos_similarity.csv')
df

# 質問の回答をリストに格納
ans = []
for i in range(len(df.columns)):
  x = df.iloc[:, i].values
  ans.append(x)

# print(ans)

def cos_similarity(ans):
  ans_list = ["使用するメンバーのリスト"]
  list_len = len(ans_list)
  
  for cp in range(list_len): #比較する人を指定
    cos_list = []
    for cped in range(list_len): #比較される人を指定
      cos = 1 - cosine(ans[cp], ans[cped])
      if cos == 1: #類似度が１になるのは自分だけなのでmax関数を使うために一番値を低くする
        cos -= 100
      cos_list.append(cos) #コサイン類似度をリストに追加

    max_index = cos_list.index(max(cos_list)) #一番類似度が高いところのインデックスを取得
    print(f"{ans_list[cp]}と一番近い人は{ans_list[max_index]}で類似度は{cos_list[max_index]}です")
    
# x = [0,1,1,1,1,1,1]
# y = [1,1,0,1,0,1,0]
# z = [1,0,1,1,1,1,1]
# a = [0,0,0,1,0,0,0]
# b = [1,1,1,0,0,0,1]
# c = [0,0,1,1,1,1,1]

cos_similarity(ans)